name: Build /weeknote pages

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - master

env:
  DLB_BOT_EMAIL: ${{ secrets.DLB_BOT_EMAIL }}
  DLB_BOT_TOKEN: ${{ secrets.DLB_BOT_TOKEN }}
  DLB_BOT_USERNAME: ${{ secrets.DLB_BOT_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Setup git
      run: |
        git config user.email "${DLB_BOT_EMAIL}"
        git config user.name "${DLB_BOT_USERNAME}"
        git remote set-url origin https://${DLB_BOT_USERNAME}:${DLB_BOT_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git checkout master
    - name: Install dependencies
      run: npm install
    - name: Build /weeknote pages
      run: npm run prestart
    - name: Commit files
      run: |
        git add docs
        git diff --quiet && git diff --staged --quiet || (git commit -m "Build /weeknote for $(date +%F)"; git push origin master)
